# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_create_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
            preserve_default=False,
        ),
    ]
